sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port:  
    database:  
    username:  
    password:  
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:  
    access-key-secret:  
    bucket-name:  
  redis:
    host: localhost
    port:  
    password:  
    database: 10
  wechat:
    appid:  
    secret:  
    mchid:
    mchSerialNo :
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
  shop:
    address:  
  baidu:
    ak:  
